apiVersion: v1
kind: ConfigMap
metadata:
  name: sillytavern-config
  namespace: sillytavern
data:
  config.yaml: |
    whitelistMode: false
    basicAuthMode: true
    basicAuthUser:
      username: "admin"
      password: "SuperS3cret!"  # Replace with a strong password
    listen: true
    listenHost: "0.0.0.0"
    port: 8000
