apiVersion: apps/v1
kind: Deployment
metadata:
  name: sillytavern
  namespace: sillytavern
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sillytavern
  template:
    metadata:
      labels:
        app: sillytavern
    spec:
      initContainers:
      - name: init-data
        image: busybox:1.36
        command: ["sh", "-c", "mkdir -p /data && chown 1000:1000 /data && chmod 755 /data && ls -ld /data"]
        volumeMounts:
        - name: data-volume
          mountPath: /data
      containers:
      - name: sillytavern
        image: ghcr.io/sillytavern/sillytavern:latest
        ports:
        - containerPort: 8000
        env:
        - name: HOST
          value: "0.0.0.0"
        volumeMounts:
        - name: data-volume
          mountPath: /home/node/app/data
        - name: config-volume
          mountPath: /home/node/app/config.yaml
          subPath: config.yaml
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: sillytavern-pvc
      - name: config-volume
        configMap:
          name: sillytavern-config
          items:
          - key: config.yaml
            path: config.yaml
